# Generated by Django 5.1.6 on 2025-02-20 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slot_name', models.CharField(help_text="Nome generico per gli slot (es. 'Materia/Docente')", max_length=255)),
                ('slot_description', models.CharField(blank=True, help_text="Descrizione/istruzioni per la scelta dello slot (es. 'Seleziona il nome della disciplina/Docente di tua scelta')", max_length=255)),
                ('allow_multiple_slots', models.BooleanField(default=False, help_text="Se True, l'utente può prenotare più di uno slot")),
                ('allowed_groups', models.ManyToManyField(blank=True, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('available_seats', models.PositiveIntegerField(default=0)),
                ('date_opening', models.DateTimeField()),
                ('date_closing', models.DateTimeField()),
                ('booking_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='PrenotazioniTesi.bookingplan')),
            ],
        ),
        migrations.CreateModel(
            name='BookingReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reservation_code', models.CharField(blank=True, max_length=64, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('booking_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='PrenotazioniTesi.bookingslot')),
            ],
            options={
                'unique_together': {('user', 'booking_slot')},
            },
        ),
    ]
