# Generated by Django 5.1.6 on 2025-02-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrenotazioniTesi', '0002_rename_slot_description_bookingplan_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingslot',
            name='subject',
            field=models.CharField(blank=True, help_text="Nome della materia dello slot (es. 'Materia')", max_length=255),
        ),
        migrations.AlterField(
            model_name='bookingslot',
            name='name',
            field=models.CharField(help_text="Nome generico per gli slot (es. 'Docente')", max_length=255),
        ),
    ]
