# Generated by Django 5.1.6 on 2025-02-26 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrenotazioniTesi', '0003_bookingslot_subject_alter_bookingslot_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingslot',
            old_name='name',
            new_name='tutor',
        ),
    ]
