# Generated by Django 5.1.6 on 2025-02-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrenotazioniTesi', '0004_rename_name_bookingslot_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingreservation',
            name='thesis_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
