# Generated by Django 5.1.6 on 2025-02-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrenotazioniTesi', '0005_bookingreservation_thesis_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingslot',
            name='tutor',
        ),
        migrations.AlterField(
            model_name='bookingslot',
            name='subject',
            field=models.CharField(help_text="Nome della materia dello slot (es. 'Materia/Docente')", max_length=255),
        ),
    ]
